### ISSUE TITLE
Windows: Linking errors with libmccs_stubs.a

### ISSUE THREAD

**Issue by bryphe** [AltGr/ocaml-mccs#16]
We're using this project on `esy` as part of our solver infrastructure: https://github.com/andreypopp/esy-solve-cudf , and it works great! We're now working to enable this solver on Windows, however, and we hit a linking error when building that `esy-solve-cudf` project:

```
** Cannot resolve symbols for C:/Users/bryph/.esy/3_/i/opam__slash__mccs-1.1+8-e4af6af7/lib\mccs\libmccs_stubs.a(lexagregate_combiner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 _ZTVN10__cxxabiv117__class_type_infoE
 _ZTVN10__cxxabiv121__vmi_class_type_infoE
```

It looks like these are RTTI symbols.

**Comment by dra27** [comment]
You need a patched flexlink to support C++ linking - the patch is in the AppVeyor script (sorry, awkward
to do the link from my phone)

**Comment by bryphe** [comment]
Thanks @dra27 ! Got it - I'll test it out and see if that fixes my issue. 👍

**Comment by bryphe** [comment]
Confirmed it's fixed when I brought in your PR https://github.com/alainfrisch/flexdll/pull/48 for `flexdll` - no other compiler flags needed. Thanks again @dra27 !
