### ISSUE TITLE
mccs glpk build fails in opam build with object size overflow

### ISSUE THREAD

**Issue by donncave** [AltGr/ocaml-mccs#31]
ocamlc src_ext/mccs/src/glpk/wclique1.o
src_ext/mccs/src/glpk/misc/wclique1.c: In function '_glp_wclique1':
src_ext/mccs/src/glpk/misc/wclique1.c:121:7: warning: 'memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
src_ext/mccs/src/glpk/misc/wclique1.c:123:7: warning: 'memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]

Platform is Haiku x86_64 - a POSIX operating system on 64 bit intel.  Casual look at the code led to a function glp_create_graph(), I can't find the source for this - but I suppose I'm on the wrong track there, in that this is a compile time error so should have nothing to do with values computed by the program.

mccs is in the src_ext collection of opam dependencies.  Appears to be version 1.1+11, Dec 2019.

**Comment by AltGr** [comment]
I guess this should be reported here: https://www.gnu.org/software/glpk
We are building with dune but I reproduce these warnings using the original Makefiles.

I don't understand the title "fails to build" as this is just a warning though ?
